#Most of the comments are from the traefik documentation
#https://doc.traefik.io/traefik/user-guides/docker-compose/basic-example/

#I'm using Porkbun here for the DNS challenge.

services:
  traefik:
    image: traefik:v3.0
    container_name: ${CONTAINER_NAME}
    hostname: ${HOSTNAME}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:80
      - 8080:8080
      - 443:443
      #- 444:444
      # - 443:443/tcp # Uncomment if you want HTTP3
      # - 443:443/udp # Uncomment if you want HTTP3
    command:
      - "--providers.docker"
      - "--log.level=DEBUG"
      - "--log.filePath=/logs/traefik.log"
  # Traefik will listen on port 8080 by default for API request.
      - "--api.insecure=true"
      - "--providers.docker=true"
  # Do not expose containers unless explicitly told so
      - "--providers.docker.exposedbydefault=false"
  # Traefik will listen to incoming request on the port 80 (HTTP)
      - "--entryPoints.web.address=:80"     
    environment:
      PORKBUN_API_KEY: ${PORKBUN_API_KEY}
      PORKBUN_SECRET_API_KEY: ${PORKBUN_SECRET_API_KEY}
      TRAEFIK_DASHBOARD_CREDENTIALS: ${TRAEFIK_DASHBOARD_CREDENTIALS}
      TZ: ${TZ}
    env_file: .env # use .env
    volumes: #to adapt with your own volumes/folders structure
      - ${PATH_CONF}/traefik.yml:/traefik.yml:ro
      - ${PATH_VOL}/:/etc/traefik/
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${PATH_CONF}/acme.json:/acme.json
      - /etc/localtime:/etc/localtime:ro
      - ${PATH_VOL}/logs/:/logs/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`${SUBDOMAIN_NAME}`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_DASHBOARD_CREDENTIALS}"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`${SUBDOMAIN_NAME}`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=porkbun"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=${DOMAIN_NAME}"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.${DOMAIN_NAME}"
      - "traefik.http.routers.traefik-secure.service=api@internal"

networks:
  proxy:
    external: true
